# Generated by Django 3.1.3 on 2021-05-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_threatinitial_angle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatinitial',
            name='angle',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
