# Generated by Django 3.1.2 on 2020-11-28 18:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PakAdm3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('id_0', models.BigIntegerField(blank=True, null=True)),
                ('iso', models.CharField(blank=True, max_length=3, null=True)),
                ('name_0', models.CharField(blank=True, max_length=75, null=True)),
                ('id_1', models.BigIntegerField(blank=True, null=True)),
                ('name_1', models.CharField(blank=True, max_length=75, null=True)),
                ('id_2', models.BigIntegerField(blank=True, null=True)),
                ('name_2', models.CharField(blank=True, max_length=75, null=True)),
                ('id_3', models.BigIntegerField(blank=True, null=True)),
                ('name_3', models.CharField(blank=True, max_length=75, null=True)),
                ('type_3', models.CharField(blank=True, max_length=50, null=True)),
                ('engtype_3', models.CharField(blank=True, max_length=50, null=True)),
                ('nl_name_3', models.CharField(blank=True, max_length=75, null=True)),
                ('varname_3', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'PAK_adm3',
                'managed': False,
            },
        ),
    ]
