# Generated by Django 3.1.3 on 2020-12-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('model', models.CharField(max_length=75)),
                ('typ', models.CharField(max_length=75)),
                ('lat', models.FloatField()),
            ],
        ),
    ]
