# Generated by Django 3.1.3 on 2020-12-19 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gisapp', '0002_threatvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threatvalue',
            name='lat',
        ),
    ]
