# Generated by Django 3.1.3 on 2021-05-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisapp', '0006_auto_20210509_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefendedAssetLoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=16, max_digits=22)),
                ('lon', models.DecimalField(decimal_places=16, max_digits=22)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
