# Generated by Django 3.1.3 on 2021-05-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisapp', '0007_defendedassetloc'),
    ]

    operations = [
        migrations.AddField(
            model_name='defendedassetloc',
            name='vitality',
            field=models.IntegerField(null=True),
        ),
    ]
