# Generated by Django 3.1.3 on 2021-05-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisapp', '0008_defendedassetloc_vitality'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatorEssential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulationTime', models.IntegerField(default=10)),
                ('numberOfThreats', models.IntegerField(default=4)),
            ],
        ),
    ]
